### ISSUE TITLE
Unable to Find Rabbit MQ Docker Image

### ISSUE THREAD

**Issue by pachori91** [datakaveri/iudx-deployment#167]
Hi Team,

I am trying to setup databrober instance by following https://github.com/datakaveri/iudx-deployment/tree/master/Docker-Swarm-deployment/single-node/databroker

As mentioned in databroker-stack.yml RMQ Image **rabbitmq:3.10.5-management** is not avaibale on docker repo.
and also tried with command **docker build -f backup/Dockerfile -t ghcr.io/datakaveri/rabbitmq-backup:1.0 backup/** but it is stuck as per below logs - 
  
root@horizon:~/iudx-deployment/Docker-Swarm-deployment/single-node/databroker# docker build -f backup/Dockerfile -t ghcr.io/datakaveri/rabbitmq-backup:1.0 backup/
Sending build context to Docker daemon  9.216kB
Step 1/5 : FROM python:3-alpine
 ---> ce4168535f30
Step 2/5 : WORKDIR /usr/share/app
 ---> Using cache
 ---> d0c1aa8e54ae
Step 3/5 : RUN apk update && apk add curl && apk add openssh-client && pip install --upgrade pip && pip install watchdog
 ---> Running in 8b4692cf0ce6
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz

Can you guys please suggest me correct image path so that i can proceed further.

Thanks
Deepak Kumar

**Comment by karun-singh** [comment]
Hi Deepak,

The [rabbitmq:3.10.5-management](https://hub.docker.com/layers/rabbitmq/library/rabbitmq/3.10.5-management/images/sha256-650c7e0093842739ddfaadec0d45946c052dba42941bd5c0a082cbe914451c25?context=explore) is available on DockerHub and I'm able to pull using `docker pull rabbitmq:3.10.5-management`. Also, the build is working as expected for us. 
It seems like the machine you're working on might not be connected to the internet or having similar issues. Can you check whether that is the case.

**Comment by pachori91** [comment]
Hi Karun,

Thanks for reply. Yes RMQ Image rabbitmq:3.10.5-management is available.

my mistake, i mentioned wrong image name in my question.

But my actual question is about the image ghcr.io/datakaveri/rabbitmq-backup:1.0 which is not available.
we need this image for backup service as per Databroker installation document.
can you please provide me correct path for same image?

One more thing, for now i just setup Rabbit MQ service, and ignored backup service.
So What will be impact if backup service is not up. Will it functionally effect my installation? 

Thanks
Deepak Kumar

**Comment by karun-singh** [comment]
Hi Deepak,

The rabbitmq-backup image isn't publicly hosted so you'll have to build it locally as suggested in the [installation guide](https://github.com/datakaveri/iudx-deployment/tree/master/Docker-Swarm-deployment/single-node/databroker#docker-image). 

The backup service backs up Rabbitmq definitions files to another VM using the SCP command whenever there is a change in queues, users, and exchanges. It does not affect RMQ functionality.

**Comment by abhi4578** [comment]
As this resolved, closing the issue
