### ISSUE TITLE
1.1 Keycloak deployment in Docker swarm

### ISSUE THREAD

**Issue by abhi4578** [datakaveri/iudx-deployment#59]
- Bringing up keycloak through use of [keycloak bitnami image](https://github.com/bitnami/bitnami-docker-keycloak)  , version 14.0.0
- Use [bitnami postgres image](https://github.com/bitnami/bitnami-docker-postgresql) and connect the keycloak with the postgres. Can be tested , by seeing if the keycloak related tables are created.
-  Migrate current auth-cred-db stack file to postgres stack file with image and other config related changes.
- Bring a nginx proxy in-front of keycloak and test if its working. Set up reverse proxy, ssl, rate limits , refer [ keycloak official docs](https://www.keycloak.org/docs/latest/server_installation/#_setting-up-a-load-balancer-or-proxy), [blog](https://itnext.io/nginx-as-reverse-proxy-in-front-of-keycloak-21e4b3f8ec53)
   -  Verifying the configuration https://www.keycloak.org/docs/latest/server_installation/#verifying-the-configuration
- Automate realm creation using imports. Create a realm , configure with general settings and export it and then import that in deployment and need to configure minimal things only like client secret, smtp/optional things.

**Comment by abhi4578** [comment]
The folder structure and files - stack files, configs, secrets can follow this structure https://github.com/datakaveri/iudx-deployment/tree/master/Docker-Swarm-deployment/single-node/auth-cred-db

**Comment by abhi4578** [comment]
It would be better, to create a  [local docker swarm with overlay network on your machine](https://github.com/datakaveri/iudx-deployment/blob/master/docs/swarm-setup.md) -  and write a basic stack file to bring up keycloak . Try accessing the kyelcoak over  tour local browser and login. This would be the first step in bringing the keycloak server

**Comment by hackcoderr** [comment]
completed the docker swarm setup https://github.com/hackcoderr/iudx-deployment/tree/master/keycloak @abhi4578
