### ISSUE TITLE
1.3 Auth server deployment in Docker Swarm

### ISSUE THREAD

**Issue by abhi4578** [datakaveri/iudx-deployment#62]
- Orchestrate authorization server in docker swarm 
- Add nginx proxy in front - centralised nginx model. 
- Add some test cases to see end-to-end working

**Comment by hackcoderr** [comment]
@abhi4578 please check out the [Auth server doc](https://github.com/hackcoderr/iudx-deployment/tree/auth-server/Docker-Swarm-deployment/single-node/auth-server) if any change is required, please mention them, as well as check the pull request also.

**Comment by abhi4578** [comment]
- AAA server github repo :  https://github.com/datakaveri/iudx-aaa-server. Please go through the configs, docker-compose and orchestrate the AAA server accordingly in docker swarm @namanmanish
